# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_dmis_field_report_responsetools'),
    ]

    operations = [
        migrations.CreateModel(
            name='surge_heops_deployments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(null=True)),
                ('startdate_accuracy', models.CharField(max_length=255)),
                ('enddate', models.DateField(null=True)),
                ('enddate_accuracy', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('disaster', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('deployed_role', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
